baseurl = "https://kingk22.xyz/"
languageCode = "en-us"
title = "Kingk22"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "Hello Friend"
  icon = "favicon.png"

# [params.logo]
#   path = "/img/your-example-logo.svg"
#   alt = "your_example_logo"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "not-about"
    name = "Not-About"
    url = "/not-about"
